"""empty message

Revision ID: 00ee1ba810d9
Revises: 1311c7d336d7
Create Date: 2019-08-29 19:41:13.493596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ee1ba810d9'
down_revision = '1311c7d336d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articlelabel', sa.Column('article', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articlelabel', 'article', ['article'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articlelabel', type_='foreignkey')
    op.drop_column('articlelabel', 'article')
    # ### end Alembic commands ###
