"""empty message

Revision ID: 0be1e4246469
Revises: ab50197dcd36
Create Date: 2019-08-31 19:46:33.060688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be1e4246469'
down_revision = 'ab50197dcd36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('alabel_ibfk_3', 'alabel', type_='foreignkey')
    op.create_foreign_key(None, 'alabel', 'article', ['articleid'], ['id'], ondelete='CASCADE')
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'article', ['articleid'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_1', 'comment', 'article', ['articleid'], ['id'])
    op.drop_constraint(None, 'alabel', type_='foreignkey')
    op.create_foreign_key('alabel_ibfk_3', 'alabel', 'article', ['articleid'], ['id'])
    # ### end Alembic commands ###
