"""empty message

Revision ID: 1311c7d336d7
Revises: c9c64c12294d
Create Date: 2019-08-29 13:51:19.467807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1311c7d336d7'
down_revision = 'c9c64c12294d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articlelabel', sa.Column('articleid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articlelabel', 'articleid')
    # ### end Alembic commands ###
