"""empty message

Revision ID: 1f7900dfab9c
Revises: 7ec9d3d55cd1
Create Date: 2019-08-31 20:03:36.603232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f7900dfab9c'
down_revision = '7ec9d3d55cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_aboutme_userid', table_name='aboutme')
    op.drop_table('aboutme')
    op.add_column('user', sa.Column('msg', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'msg')
    op.create_table('aboutme',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('userid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('imgpath', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('msg', mysql.VARCHAR(length=5000), nullable=True),
    sa.Column('info', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('yuming', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('beianhao', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], name='aboutme_ibfk_1'),
    sa.PrimaryKeyConstraint('id', 'userid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_aboutme_userid', 'aboutme', ['userid'], unique=False)
    # ### end Alembic commands ###
