"""empty message

Revision ID: 6e8e5c75c3ba
Revises: 90047ba09e72
Create Date: 2019-08-29 20:32:12.170543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8e5c75c3ba'
down_revision = '90047ba09e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lmessage', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lmessage', 'email')
    # ### end Alembic commands ###
