"""empty message

Revision ID: 7b0717a838f6
Revises: 00ee1ba810d9
Create Date: 2019-08-29 19:44:17.695132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b0717a838f6'
down_revision = '00ee1ba810d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articlelabel_ibfk_1', 'articlelabel', type_='foreignkey')
    op.create_foreign_key(None, 'articlelabel', 'article', ['articleid'], ['id'])
    op.drop_column('articlelabel', 'article')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articlelabel', sa.Column('article', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articlelabel', type_='foreignkey')
    op.create_foreign_key('articlelabel_ibfk_1', 'articlelabel', 'article', ['article'], ['id'])
    # ### end Alembic commands ###
