"""empty message

Revision ID: 90047ba09e72
Revises: 7b0717a838f6
Create Date: 2019-08-29 20:29:07.341971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90047ba09e72'
down_revision = '7b0717a838f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lmessage', sa.Column('msgback', sa.String(length=1500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lmessage', 'msgback')
    # ### end Alembic commands ###
