"""empty message

Revision ID: c9c64c12294d
Revises: 793ac0bc453f
Create Date: 2019-08-28 19:41:12.735957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c64c12294d'
down_revision = '793ac0bc453f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admintoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.Column('outtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admintoken')
    # ### end Alembic commands ###
