"""empty message

Revision ID: ce6479f7532d
Revises: 2afd67efabca
Create Date: 2019-08-31 15:34:05.727205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce6479f7532d'
down_revision = '2afd67efabca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articlelabel_ibfk_1', 'articlelabel', type_='foreignkey')
    op.drop_column('articlelabel', 'articleid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articlelabel', sa.Column('articleid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('articlelabel_ibfk_1', 'articlelabel', 'article', ['articleid'], ['id'])
    # ### end Alembic commands ###
